
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - unused
    - revive
  disable:
    - gosimple

issues:
  exclude-use-default: true # false: 自动启用默认启用的linters 命令：golangci-lint linters 查看默认启用的linter