run:
  timeout: 3m
  tests: true

linters:
  enable:
#    - govet
#    - errcheck
#    - staticcheck
#    - gofmt
#    - goimports
#    - gocyclo
    - unused
#    - revive

issues:
  exclude-use-default: false