// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"dex/app/api/internal/handler/auth"
	"net/http"

	"dex/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: APIHandler(serverCtx),
			},
		},
	)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:wallet_address/nonce",
				Handler: auth.GetNonceByAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallet/login",
				Handler: auth.LoginByWalletAddress(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"))
}
